name: Update README and assets
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  update:
    name: Update README and assets
    runs-on: ['hyperenv', 'medium-eu-west-1']
    steps:
    - uses: actions/checkout@v4
    - name: Copy README.txt to root
      run: |
        cp plugin/README.txt .
    - uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        ASSETS_DIR: '.wordpress-org'
        README_NAME: 'README.txt'
        IGNORE_OTHER_FILES: true
        SLUG: attachmentav